(() => {
  const visibilityStyle = document.createElement('style');
  visibilityStyle.textContent = '[hidden]{display:none!important}';
  document.head.appendChild(visibilityStyle);
  const apiRoot = `${String(window.__AKIO_API_BASE_URL__ || '').replace(/\/$/,'')}/api/social`;
  const state = { user:null, postImage:'', avatarImage:'', removeAvatar:false, currentProfile:null, activeConversation:null };
  const $ = (selector,root=document) => root.querySelector(selector);
  const $$ = (selector,root=document) => [...root.querySelectorAll(selector)];
  const esc = value => String(value ?? '').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const date = value => new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(`${value}Z`));

  function avatar(element,user){element.style.backgroundImage=user?.avatar?`url(${user.avatar})`:'';element.textContent=user?.avatar?'':String(user?.displayName||user?.username||'?')[0].toUpperCase()}
  function avatarHtml(user,classes='avatar'){return `<div class="${classes}"${user?.avatar?` style="background-image:url(${user.avatar})"`:''}>${user?.avatar?'':esc(String(user?.displayName||user?.username||'?')[0].toUpperCase())}</div>`}
  function toast(text){const element=$('#toast');element.textContent=text;element.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>element.classList.remove('show'),2600)}
  async function api(path,options={}){const response=await fetch(`${apiRoot}${path}`,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await response.json().catch(()=>({error:'Invalid server response.'}));if(!response.ok)throw new Error(data.error||'Request failed.');return data}
  function formObject(form){return Object.fromEntries(new FormData(form).entries())}
  async function imageData(file,maxDimension=1600){
    if(!file)return '';
    if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('Use a PNG, JPEG, or WebP image.');
    if(file.size>15_000_000)throw new Error('That image is too large. Choose one under 15 MB.');
    const source=URL.createObjectURL(file);
    try{
      const image=await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('Could not open that image.'));img.src=source});
      const scale=Math.min(1,maxDimension/Math.max(image.naturalWidth,image.naturalHeight));
      const canvas=document.createElement('canvas');
      canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));
      const context=canvas.getContext('2d');context.imageSmoothingEnabled=true;context.imageSmoothingQuality='high';context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(image,0,0,canvas.width,canvas.height);
      let output=canvas.toDataURL('image/jpeg',.86);if(output.length>1_950_000)output=canvas.toDataURL('image/jpeg',.68);
      if(output.length>1_950_000)throw new Error('The image could not be reduced enough. Try a smaller photo.');
      return output;
    } finally { URL.revokeObjectURL(source); }
  }
  function setUser(user){state.user=user;$('#authView').hidden=!!user;$('#appView').hidden=!user;if(!user)return;$('#sideName').textContent=user.displayName;$('#sideUsername').textContent=`@${user.username}`;avatar($('#sideAvatar'),user);avatar($('#composerAvatar'),user);$('#adminNav').hidden=user.role!=='admin'}
  async function bootstrap(){try{const {user}=await api('/me');setUser(user);if(user){showView('feed');await Promise.all([loadFeed(),loadNotificationBadge(),loadSuggestions()])}}catch{setUser(null)}}

  $$('.auth-tabs button').forEach(button=>button.onclick=()=>{$$('.auth-tabs button').forEach(item=>item.classList.toggle('active',item===button));$('#loginForm').hidden=button.dataset.authTab!=='login';$('#registerForm').hidden=button.dataset.authTab!=='register';$('#authStatus').textContent=''});
  async function authSubmit(form,path){const status=$('#authStatus');status.textContent='';try{const {user}=await api(path,{method:'POST',body:JSON.stringify(formObject(form))});setUser(user);form.reset();showView('feed');await Promise.all([loadFeed(),loadSuggestions()])}catch(error){status.textContent=error.message}}
  $('#loginForm').onsubmit=event=>{event.preventDefault();authSubmit(event.currentTarget,'/login')};
  $('#registerForm').onsubmit=event=>{event.preventDefault();authSubmit(event.currentTarget,'/register')};
  $('#logoutButton').onclick=async()=>{await api('/logout',{method:'POST'});setUser(null)};

  function showView(name){$$('[data-view]').forEach(item=>item.classList.toggle('active',item.dataset.view===name));$$('.view').forEach(item=>item.hidden=item.id!==`${name}View`);if(name==='feed')loadFeed();if(name==='search')setTimeout(()=>$('#searchForm input').focus(),30);if(name==='messages')loadConversations();if(name==='notifications')loadNotifications();if(name==='profile')loadProfile(state.user.id);if(name==='admin')loadAdmin()}
  function showViewOnly(name){$$('[data-view]').forEach(item=>item.classList.toggle('active',item.dataset.view===name));$$('.view').forEach(item=>item.hidden=item.id!==`${name}View`)}
  $$('[data-view]').forEach(item=>item.onclick=()=>showView(item.dataset.view));
  $$('[data-compose]').forEach(item=>item.onclick=()=>{showView('feed');$('#postForm textarea').focus()});

  $('#postImage').onchange=async event=>{try{state.postImage=await imageData(event.target.files[0],1600);$('#postPreview').style.backgroundImage=`url(${state.postImage})`;$('#postPreview').hidden=false}catch(error){toast(error.message);event.target.value=''}};
  $('#removePostImage').onclick=()=>{state.postImage='';$('#postImage').value='';$('#postPreview').hidden=true;$('#postPreview').style.backgroundImage=''};
  $('#postForm').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,status=$('#postStatus');status.textContent='Posting…';try{await api('/posts',{method:'POST',body:JSON.stringify({content:form.content.value,image:state.postImage})});form.reset();state.postImage='';$('#postPreview').hidden=true;status.textContent='';toast('Post published');await loadFeed()}catch(error){status.textContent=error.message}};
  async function loadFeed(){const list=$('#feedList');list.innerHTML='<div class="empty-state">Loading community posts…</div>';try{const {posts}=await api('/feed');renderPosts(list,posts)}catch(error){list.innerHTML=`<div class="empty-state">${esc(error.message)}</div>`}}
  function renderPosts(container,posts){container.innerHTML=posts.length?'':'<div class="empty-state">No posts yet. Start the conversation.</div>';posts.forEach(post=>container.appendChild(postElement(post)))}
  function postElement(post){
    const article=document.createElement('article');article.className='post';article.dataset.postId=post.id;
    const own=post.authorId===state.user.id||state.user.role==='admin';
    article.innerHTML=`<div class="post-head">${avatarHtml(post)}<div class="post-author"><strong>${esc(post.displayName)}</strong><small>@${esc(post.username)} · ${date(post.createdAt)}</small></div>${own?'<button class="post-menu" title="Delete post">•••</button>':''}</div><p class="post-content">${esc(post.content)}</p>${post.image?`<img class="post-image" src="${post.image}" alt="Photo shared by ${esc(post.displayName)}">`:''}<div class="post-actions"><button class="like ${post.liked?'active':''}">♥ <span>${post.likeCount}</span></button><button class="comment-toggle">◯ <span>${post.commentCount}</span></button><button class="share">↗ Share</button></div><div class="comments" hidden><div class="comment-list"></div><form class="comment-form"><input maxlength="500" placeholder="Write a comment…" required><button>↑</button></form></div>`;
    $('.post-author',article).onclick=()=>loadProfile(post.authorId);$('.post-head>.avatar',article).onclick=()=>loadProfile(post.authorId);
    $('.post-menu',article)?.addEventListener('click',()=>confirmDelete(async()=>{await api(`/posts/${post.id}`,{method:'DELETE'});article.remove();toast('Post deleted')}));
    $('.like',article).onclick=async event=>{const button=event.currentTarget;try{const result=await api(`/posts/${post.id}/like`,{method:'POST'});button.classList.toggle('active',result.liked);$('span',button).textContent=result.count}catch(error){toast(error.message)}};
    $('.share',article).onclick=async()=>{const url=`${location.origin}${location.pathname}#post-${post.id}`;try{await navigator.clipboard.writeText(url);toast('Post link copied')}catch{toast('Copy unavailable')}};
    $('.comment-toggle',article).onclick=()=>toggleComments(article,post.id);
    $('.comment-form',article).onsubmit=async event=>{event.preventDefault();const input=$('input',event.currentTarget);try{await api(`/posts/${post.id}/comments`,{method:'POST',body:JSON.stringify({content:input.value})});input.value='';await loadComments(article,post.id);const count=$('.comment-toggle span',article);count.textContent=Number(count.textContent)+1}catch(error){toast(error.message)}};
    return article;
  }
  async function toggleComments(article,id){const section=$('.comments',article);section.hidden=!section.hidden;if(!section.hidden)await loadComments(article,id)}
  async function loadComments(article,id){const list=$('.comment-list',article);const {comments}=await api(`/posts/${id}/comments`);list.innerHTML=comments.map(comment=>`<div class="comment" data-comment-id="${comment.id}">${avatarHtml(comment)}<div><strong>${esc(comment.displayName)}</strong><p>${esc(comment.content)}</p><small>${date(comment.createdAt)}</small></div>${comment.userId===state.user.id||state.user.role==='admin'?'<button title="Delete comment">×</button>':''}</div>`).join('');$$('.comment button',list).forEach(button=>button.onclick=()=>confirmDelete(async()=>{await api(`/comments/${button.closest('.comment').dataset.commentId}`,{method:'DELETE'});button.closest('.comment').remove();toast('Comment deleted')}))}
  let confirmAction=null;function confirmDelete(action){confirmAction=action;$('#confirmDialog').showModal()}$('[data-confirm-cancel]').onclick=()=>$('#confirmDialog').close();$('[data-confirm-ok]').onclick=async()=>{try{await confirmAction()}catch(error){toast(error.message)}finally{$('#confirmDialog').close()}};

  let searchTimer;$('#searchForm input').oninput=event=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>searchUsers(event.target.value),250)};$('#searchForm').onsubmit=event=>{event.preventDefault();searchUsers(event.currentTarget.q.value)};
  async function searchUsers(query){const box=$('#searchResults');if(!query.trim()){box.className='people-list empty-state';box.textContent='Search for someone to connect with.';return}box.className='people-list';try{const {users}=await api(`/search?q=${encodeURIComponent(query)}`);box.innerHTML=users.length?'':'<div class="empty-state">No people found.</div>';users.forEach(user=>box.appendChild(personRow(user)))}catch(error){box.innerHTML=`<div class="empty-state">${esc(error.message)}</div>`}}
  function personRow(user){const row=document.createElement('div');row.className='person-row';row.innerHTML=`${avatarHtml(user)}<div><strong>${esc(user.displayName)}</strong><span>@${esc(user.username)} · ${esc(user.bio||'New to Loopline')}</span></div><div><button class="profile-button">Profile</button> <button class="message-button">Message</button></div>`;$('.profile-button',row).onclick=()=>loadProfile(user.id);$('.message-button',row).onclick=()=>startConversation(user.id);return row}
  async function loadSuggestions(){try{const {users,stats}=await api('/suggestions');const rail=$('#suggestionsList'),strip=$('#communityStrip');rail.innerHTML='';strip.innerHTML='';users.forEach(user=>{const row=document.createElement('div');row.className='suggestion-row';row.innerHTML=`${avatarHtml(user)}<div><strong>${esc(user.displayName)}</strong><span>@${esc(user.username)}</span></div><button>View</button>`;row.querySelector('button').onclick=()=>loadProfile(user.id);rail.appendChild(row);const story=document.createElement('button');story.className='community-person';story.innerHTML=`${avatarHtml(user)}<span>${esc(user.displayName.split(' ')[0])}</span>`;story.onclick=()=>loadProfile(user.id);strip.appendChild(story)});if(!users.length)rail.innerHTML='<div class="empty-state">Invite someone into your loop.</div>';$('#communityPulse').textContent=`${stats.people} ${stats.people===1?'person':'people'} · ${stats.posts} ${stats.posts===1?'post':'posts'} shared`;}catch{$('#suggestionsList').innerHTML='<div class="empty-state">Discover people soon.</div>'}}

  async function loadProfile(id){showViewOnly('profile');const content=$('#profileContent');content.innerHTML='<div class="empty-state">Loading profile…</div>';try{const {profile,posts}=await api(`/users/${id}`);if(!profile)throw new Error('Profile not found.');state.currentProfile=profile;content.innerHTML=`<div class="profile-cover" style="--cover:${esc(profile.coverColor||'#6856e8')}"></div><div class="profile-header"><div class="profile-top">${avatarHtml(profile,'avatar profile-avatar')}<button>${id===state.user.id?'Edit profile':'Message'}</button></div><h1>${esc(profile.displayName)}</h1><span>@${esc(profile.username)}</span><p>${esc(profile.bio||'No bio yet.')}</p><div class="profile-meta">Joined ${new Intl.DateTimeFormat(undefined,{month:'long',year:'numeric'}).format(new Date(`${profile.createdAt}Z`))}</div><div class="profile-stats"><div><strong>${posts.length}</strong> <span>${posts.length===1?'post':'posts'}</span></div></div></div><div class="profile-posts"></div>`;$('.profile-top button',content).onclick=id===state.user.id?openProfileEditor:()=>startConversation(id);renderPosts($('.profile-posts',content),posts)}catch(error){content.innerHTML=`<div class="empty-state">${esc(error.message)}</div>`}}
  function selectCover(color){const form=$('#profileForm');form.coverColor.value=color;$$('[data-cover-color]',form).forEach(button=>{const selected=button.dataset.coverColor===color;button.classList.toggle('selected',selected);button.setAttribute('aria-checked',String(selected))})}
  function openProfileEditor(){const form=$('#profileForm');form.displayName.value=state.user.displayName;form.bio.value=state.user.bio||'';state.avatarImage='';state.removeAvatar=false;$('#avatarImage').value='';avatar($('#avatarPreview'),state.user);selectCover(state.user.coverColor||'#6856e8');$('.form-status',form).textContent='';$('#profileDialog').showModal()}
  $('[data-close-dialog]').onclick=()=>$('#profileDialog').close();$$('[data-cover-color]').forEach(button=>button.onclick=()=>selectCover(button.dataset.coverColor));
  $('#avatarImage').onchange=async event=>{try{state.avatarImage=await imageData(event.target.files[0],512);state.removeAvatar=false;avatar($('#avatarPreview'),{...state.user,avatar:state.avatarImage});toast('Photo ready — save your profile to apply it')}catch(error){toast(error.message);event.target.value=''}};
  $('#removeAvatar').onclick=()=>{state.avatarImage='';state.removeAvatar=true;$('#avatarImage').value='';avatar($('#avatarPreview'),{...state.user,avatar:''})};
  $('#profileForm').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,status=$('.form-status',form);status.textContent='Saving…';try{const payload=formObject(form);payload.avatar=state.avatarImage;payload.removeAvatar=state.removeAvatar;const {user}=await api('/profile',{method:'PATCH',body:JSON.stringify(payload)});state.user={...state.user,...user};setUser(state.user);$('#profileDialog').close();loadProfile(state.user.id);loadSuggestions();toast('Profile updated')}catch(error){status.textContent=error.message}};

  async function loadConversations(){const list=$('#conversationList');list.innerHTML='<div class="empty-state">Loading…</div>';try{const {conversations}=await api('/conversations');list.innerHTML=conversations.length?'':'<div class="empty-state">No conversations yet.</div>';conversations.forEach(conversation=>{const row=document.createElement('div');row.className='conversation-item';row.innerHTML=`${avatarHtml(conversation.other)}<div><strong>${esc(conversation.other?.displayName||'Conversation')}</strong><span>${esc(conversation.lastMessage||'Start a conversation')}</span></div>`;row.onclick=()=>openConversation(conversation.id,conversation.other);list.appendChild(row)})}catch(error){list.innerHTML=`<div class="empty-state">${esc(error.message)}</div>`}}
  async function startConversation(userId){try{const {conversation}=await api('/conversations',{method:'POST',body:JSON.stringify({userId})});const {profile}=await api(`/users/${userId}`);showView('messages');openConversation(conversation.id,profile)}catch(error){toast(error.message)}}
  async function openConversation(id,other){state.activeConversation=id;const panel=$('#messagePanel');panel.innerHTML=`<header class="message-header">${avatarHtml(other)}<strong>${esc(other?.displayName||'Conversation')}</strong></header><div class="message-stream"></div><form class="message-form"><input maxlength="1000" placeholder="Write a message…" required><button>↑</button></form>`;async function refresh(){const {messages}=await api(`/conversations/${id}/messages`);const stream=$('.message-stream',panel);stream.innerHTML=messages.map(message=>`<div class="bubble ${message.senderId===state.user.id?'mine':''}">${esc(message.content)}</div>`).join('');stream.scrollTop=stream.scrollHeight}await refresh();$('.message-form',panel).onsubmit=async event=>{event.preventDefault();const input=$('input',event.currentTarget);try{await api(`/conversations/${id}/messages`,{method:'POST',body:JSON.stringify({content:input.value})});input.value='';await refresh()}catch(error){toast(error.message)}}}
  $('#newConversation').onclick=()=>showView('search');
  async function loadNotificationBadge(){try{const {notifications}=await api('/notifications');const count=notifications.filter(item=>!item.is_read).length;$('#notificationBadge').textContent=count||''}catch{}}
  async function loadNotifications(){const list=$('#notificationList');try{const {notifications}=await api('/notifications');list.innerHTML=notifications.length?'':'<div class="empty-state">No notifications yet.</div>';notifications.forEach(notification=>{const row=document.createElement('div');row.className=`notification-row ${notification.is_read?'':'unread'}`;row.innerHTML=`${avatarHtml({avatar:notification.actorAvatar,displayName:notification.actorName})}<div><p>${esc(notification.message)}</p><small>${date(notification.created_at)}</small></div><span>${notification.type==='like'?'♥':notification.type==='message'?'✉':'◯'}</span>`;list.appendChild(row)})}catch(error){list.innerHTML=`<div class="empty-state">${esc(error.message)}</div>`}}
  $('#markRead').onclick=async()=>{await api('/notifications/read',{method:'POST'});$('#notificationBadge').textContent='';loadNotifications()};

  async function loadAdmin(){
    if(state.user.role!=='admin')return showView('feed');
    const box=$('#adminContent');box.innerHTML='<div class="empty-state">Loading dashboard…</div>';
    try{
      const {stats,users,posts}=await api('/admin/stats');
      box.innerHTML=`<div class="stats-grid">${Object.entries(stats).map(([key,value])=>`<article class="stat-card"><span>Total ${esc(key)}</span><strong>${value}</strong></article>`).join('')}</div><form class="search-box admin-filter"><span>⌕</span><input placeholder="Filter users or posts" autocomplete="off"></form><div class="admin-table"><div class="admin-row"><strong>User</strong><strong>Role</strong><strong>Action</strong></div>${users.map(user=>`<div class="admin-row" data-user-id="${user.id}"><span>${esc(user.displayName)} · @${esc(user.username)}</span><span>${esc(user.role)}${user.suspended?' · suspended':''}</span><button ${user.id===state.user.id?'disabled':''}>${user.suspended?'Restore':'Suspend'}</button></div>`).join('')}</div><div class="admin-table admin-posts"><div class="admin-row"><strong>Recent post</strong><strong>Author</strong><strong>Action</strong></div>${posts.map(post=>`<div class="admin-row" data-post-id="${post.id}"><span>${esc(post.content||'Image post')}</span><span>@${esc(post.username)}</span><button class="danger">Delete</button></div>`).join('')}</div>`;
      $('.admin-filter input',box).oninput=event=>{$$('.admin-row[data-user-id],.admin-row[data-post-id]',box).forEach(row=>row.hidden=!row.innerText.toLowerCase().includes(event.target.value.toLowerCase()))};
      $$('.admin-row[data-user-id] button',box).forEach(button=>button.onclick=async()=>{try{await api(`/admin/users/${button.closest('.admin-row').dataset.userId}/suspend`,{method:'POST'});loadAdmin();toast('User status updated')}catch(error){toast(error.message)}});
      $$('.admin-row[data-post-id] button',box).forEach(button=>button.onclick=()=>confirmDelete(async()=>{await api(`/posts/${button.closest('.admin-row').dataset.postId}`,{method:'DELETE'});loadAdmin();toast('Post removed by moderator')}));
    }catch(error){box.innerHTML=`<div class="empty-state">${esc(error.message)}</div>`}
  }
  bootstrap();
})();
