(() => {
  const hiddenStyle=document.createElement('style');hiddenStyle.textContent='[hidden]{display:none!important}';document.head.appendChild(hiddenStyle);
  const apiRoot=`${String(window.__AKIO_API_BASE_URL__||'').replace(/\/$/,'')}/api/social`;
  const state={user:null,token:localStorage.getItem('loopline_session')||'',postImage:'',avatarImage:'',removeAvatar:false,feedPosts:[],currentProfile:null,activeConversation:null,messagePoll:null,conversationPoll:null,messageRefresh:null};
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const icon=(name,cls='')=>`<svg class="${cls}" aria-hidden="true"><use href="#i-${name}"/></svg>`;
  const date=v=>new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(`${v}Z`));
  function avatar(el,user){el.style.backgroundImage=user?.avatar?`url(${user.avatar})`:'';el.textContent=user?.avatar?'':String(user?.displayName||user?.username||'?')[0].toUpperCase()}
  function avatarHtml(user,cls='avatar'){return `<div class="${cls}"${user?.avatar?` style="background-image:url(${user.avatar})"`:''}>${user?.avatar?'':esc(String(user?.displayName||user?.username||'?')[0].toUpperCase())}</div>`}
  function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2400)}
  async function api(path,options={}){const auth=state.token?{Authorization:`Bearer ${state.token}`}:{},res=await fetch(`${apiRoot}${path}`,{credentials:'include',headers:{'Content-Type':'application/json',...auth,...(options.headers||{})},...options});const data=await res.json().catch(()=>({error:'Invalid server response.'}));if(!res.ok)throw new Error(data.error||'Request failed.');return data}
  const formObject=form=>Object.fromEntries(new FormData(form).entries());
  async function imageData(file,max=1600){if(!file)return '';if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('Use a PNG, JPEG, or WebP image.');if(file.size>15_000_000)throw new Error('Choose an image under 15 MB.');const src=URL.createObjectURL(file);try{const img=await new Promise((ok,no)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=()=>no(new Error('Could not open that image.'));i.src=src});const scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=canvas.getContext('2d');ctx.imageSmoothingQuality='high';ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);let out=canvas.toDataURL('image/jpeg',.86);if(out.length>1_950_000)out=canvas.toDataURL('image/jpeg',.66);if(out.length>1_950_000)throw new Error('Try a smaller image.');return out}finally{URL.revokeObjectURL(src)}}
  function setUser(user){state.user=user;$('#authView').hidden=!!user;$('#appView').hidden=!user;if(!user)return;$('#sideName').textContent=user.displayName;$('#sideUsername').textContent=`@${user.username}`;avatar($('#sideAvatar'),user);avatar($('#composerAvatar'),user);$('#adminNav').hidden=user.role!=='admin'}
  async function bootstrap(){try{const {user}=await api('/me');setUser(user);if(user){showView('feed');await Promise.all([loadFeed(),loadSuggestions(),loadNotificationBadge()])}}catch{setUser(null)}}
  $$('.auth-tabs button').forEach(b=>b.onclick=()=>{$$('.auth-tabs button').forEach(x=>x.classList.toggle('active',x===b));$('#loginForm').hidden=b.dataset.authTab!=='login';$('#registerForm').hidden=b.dataset.authTab!=='register';$('#authStatus').textContent=''});
  async function authSubmit(form,path){try{const {user,token}=await api(path,{method:'POST',body:JSON.stringify(formObject(form))});state.token=token||'';if(state.token)localStorage.setItem('loopline_session',state.token);setUser(user);form.reset();showView('feed');await Promise.all([loadFeed(),loadSuggestions()])}catch(e){$('#authStatus').textContent=e.message}}
  $('#loginForm').onsubmit=e=>{e.preventDefault();authSubmit(e.currentTarget,'/login')};$('#registerForm').onsubmit=e=>{e.preventDefault();authSubmit(e.currentTarget,'/register')};$('#logoutButton').onclick=async()=>{try{await api('/logout',{method:'POST'})}finally{stopLiveUpdates();state.token='';localStorage.removeItem('loopline_session');setUser(null)}};
  function showOnly(name){$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$$('.view').forEach(x=>x.hidden=x.id!==`${name}View`)}
  function showView(name){if(name!=='messages')stopLiveUpdates();showOnly(name);if(name==='feed')loadFeed();if(name==='search'){renderExplorePeople();setTimeout(()=>$('#searchForm input').focus(),30)}if(name==='messages')startConversationUpdates();if(name==='notifications')loadNotifications();if(name==='bookmarks')loadBookmarks();if(name==='profile')loadProfile(state.user.id);if(name==='admin')loadAdmin()}
  $$('[data-view]').forEach(x=>x.onclick=()=>showView(x.dataset.view));$$('[data-compose]').forEach(x=>x.onclick=()=>{showView('feed');$('#postForm textarea').focus()});
  $('#railSearchForm').onsubmit=e=>{e.preventDefault();showView('search');$('#searchForm input').value=e.currentTarget.q.value;searchUsers(e.currentTarget.q.value)};
  $$('.feed-tabs button').forEach(b=>b.onclick=()=>{$$('.feed-tabs button').forEach(x=>x.classList.toggle('active',x===b));renderPosts($('#feedList'),b.dataset.feedFilter==='media'?state.feedPosts.filter(p=>p.image):state.feedPosts)});
  $('#emojiButton').onclick=()=>{$('#emojiMenu').hidden=!$('#emojiMenu').hidden};$$('#emojiMenu button').forEach(b=>b.onclick=()=>{const t=$('#postForm textarea');t.value+=b.textContent;t.focus();$('#emojiMenu').hidden=true});
  $('#postImage').onchange=async e=>{try{state.postImage=await imageData(e.target.files[0]);$('#postPreview').style.backgroundImage=`url(${state.postImage})`;$('#postPreview').hidden=false}catch(err){toast(err.message);e.target.value=''}};
  $('#removePostImage').onclick=()=>{state.postImage='';$('#postImage').value='';$('#postPreview').hidden=true};
  $('#postForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,status=$('#postStatus');status.textContent='Posting…';try{await api('/posts',{method:'POST',body:JSON.stringify({content:form.content.value,image:state.postImage})});form.reset();state.postImage='';$('#postPreview').hidden=true;status.textContent='';toast('Post published');loadFeed()}catch(err){status.textContent=err.message}};
  async function loadFeed(){const box=$('#feedList');box.innerHTML=skeletons();try{const {posts}=await api('/feed');state.feedPosts=posts;renderPosts(box,posts);updateTrends(posts)}catch(e){box.innerHTML=empty(e.message)}}
  async function loadBookmarks(){const box=$('#bookmarkList');box.innerHTML=skeletons();try{const {posts}=await api('/bookmarks');renderPosts(box,posts,'No bookmarks yet. Save posts to find them here.')}catch(e){box.innerHTML=empty(e.message)}}
  const skeletons=()=>'<div class="post skeleton"></div><div class="post skeleton"></div>';
  const empty=text=>`<div class="intentional-empty">${icon('sparkles')}<h2>Nothing here yet</h2><p>${esc(text)}</p></div>`;
  function renderPosts(box,posts,message='No posts yet. Start the conversation.'){box.innerHTML=posts.length?'':empty(message);posts.forEach(p=>box.appendChild(postElement(p)))}
  function postElement(post){const article=document.createElement('article');article.className='post';article.dataset.postId=post.id;const own=post.authorId===state.user.id||state.user.role==='admin';article.innerHTML=`<div class="post-head">${avatarHtml(post)}<div class="post-author"><strong>${esc(post.displayName)}</strong><small>@${esc(post.username)} · ${date(post.createdAt)}</small></div>${own?`<button class="icon-btn post-menu" aria-label="Delete post">${icon('more')}</button>`:'<span></span>'}</div>${post.content?`<p class="post-content">${esc(post.content)}</p>`:''}${post.image?`<img class="post-image" src="${post.image}" alt="Photo shared by ${esc(post.displayName)}">`:''}<div class="post-actions"><button class="like ${post.liked?'active':''}" aria-label="Like">${icon('heart')}<span>${post.likeCount||''}</span></button><button class="comment-toggle" aria-label="Comment">${icon('comment')}<span>${post.commentCount||''}</span></button><button class="share" aria-label="Share">${icon('share')}<span>Share</span></button><button class="bookmark ${post.bookmarked?'active':''}" aria-label="Bookmark">${icon('bookmark')}</button></div><div class="comments" hidden><div class="comment-list"></div><form class="comment-form"><input maxlength="500" placeholder="Write a reply…" required><button aria-label="Send">${icon('send')}</button></form></div>`;
    $('.post-author',article).onclick=$('.post-head>.avatar',article).onclick=()=>loadProfile(post.authorId);$('.post-menu',article)?.addEventListener('click',()=>confirmDelete(async()=>{await api(`/posts/${post.id}`,{method:'DELETE'});article.remove();toast('Post deleted')}));
    $('.like',article).onclick=async e=>{const button=e.currentTarget;if(button.disabled)return;button.disabled=true;try{const out=await api(`/posts/${post.id}/like`,{method:'POST'});button.classList.toggle('active',out.liked);$('span',button).textContent=out.count||''}catch(err){toast(err.message)}finally{button.disabled=false}};
    $('.bookmark',article).onclick=async e=>{const button=e.currentTarget;if(button.disabled)return;button.disabled=true;try{const out=await api(`/posts/${post.id}/bookmark`,{method:'POST'});button.classList.toggle('active',out.bookmarked);toast(out.bookmarked?'Post saved':'Bookmark removed')}catch(err){toast(err.message)}finally{button.disabled=false}};
    $('.share',article).onclick=async()=>{try{await navigator.clipboard.writeText(`${location.origin}${location.pathname}#post-${post.id}`);toast('Post link copied')}catch{toast('Copy unavailable')}};$('.comment-toggle',article).onclick=()=>toggleComments(article,post.id);
    $('.comment-form',article).onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,input=$('input',form),button=$('button',form),content=input.value.trim();if(!content||button.disabled)return;button.disabled=true;try{await api(`/posts/${post.id}/comments`,{method:'POST',body:JSON.stringify({content})});input.value='';await loadComments(article,post.id);const count=$('.comment-toggle span',article);count.textContent=String((Number(count.textContent)||0)+1)}catch(err){toast(err.message)}finally{button.disabled=false;input.focus()}};return article}
  async function toggleComments(article,id){const section=$('.comments',article);section.hidden=!section.hidden;if(!section.hidden)loadComments(article,id)}
  async function loadComments(article,id){const {comments}=await api(`/posts/${id}/comments`),box=$('.comment-list',article);box.innerHTML=comments.map(c=>`<div class="comment" data-comment-id="${c.id}">${avatarHtml(c)}<div><strong>${esc(c.displayName)}</strong><p>${esc(c.content)}</p><small>${date(c.createdAt)}</small></div>${c.userId===state.user.id||state.user.role==='admin'?`<button aria-label="Delete reply">${icon('x')}</button>`:''}</div>`).join('');$$('.comment button',box).forEach(b=>b.onclick=()=>confirmDelete(async()=>{await api(`/comments/${b.closest('.comment').dataset.commentId}`,{method:'DELETE'});b.closest('.comment').remove()}))}
  let confirmAction;function confirmDelete(action){confirmAction=action;$('#confirmDialog').showModal()}$('[data-confirm-cancel]').onclick=()=>$('#confirmDialog').close();$('[data-confirm-ok]').onclick=async()=>{try{await confirmAction()}catch(e){toast(e.message)}finally{$('#confirmDialog').close()}};
  function updateTrends(posts){const counts={};posts.forEach(p=>(p.content.match(/#[\w]+/g)||[]).forEach(tag=>counts[tag.toLowerCase()]=(counts[tag.toLowerCase()]||0)+1));let trends=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,4);if(!trends.length)trends=[['#creativity',0],['#technology',0],['#community',0]];const html=trends.map(([tag,count],i)=>`<div class="trend-row"><small>${i+1} · Trending</small><strong>${esc(tag)}</strong><span>${count?`${count} ${count===1?'post':'posts'}`:'Start the conversation'}</span></div>`).join('');$('#trendingList').innerHTML=$('#exploreTrends').innerHTML=html}
  let searchTimer;$('#searchForm input').oninput=e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>searchUsers(e.target.value),220)};$('#searchForm').onsubmit=e=>{e.preventDefault();searchUsers(e.currentTarget.q.value)};
  async function searchUsers(q){if(!q.trim())return renderExplorePeople();const box=$('#searchResults');box.innerHTML=skeletons();try{const {users}=await api(`/search?q=${encodeURIComponent(q)}`);box.innerHTML=users.length?'':empty('No people match that search.');users.forEach(u=>box.appendChild(personRow(u)))}catch(e){box.innerHTML=empty(e.message)}}
  async function renderExplorePeople(){try{const {users}=await api('/suggestions');const box=$('#searchResults');box.innerHTML='';users.forEach(u=>box.appendChild(personRow(u)));if(!users.length)box.innerHTML=empty('More people will appear as the community grows.')}catch{}}
  function personRow(user){const row=document.createElement('div');row.className='person-row';row.innerHTML=`${avatarHtml(user)}<div><strong>${esc(user.displayName)}</strong><span>@${esc(user.username)} · ${esc(user.bio||'New to Loopline')}</span></div><div><button class="btn secondary compact profile-button">View</button><button class="btn primary compact message-button">Message</button></div>`;$('.profile-button',row).onclick=()=>loadProfile(user.id);$('.message-button',row).onclick=()=>startConversation(user.id);return row}
  async function loadSuggestions(){try{const {users,stats}=await api('/suggestions'),box=$('#suggestionsList');box.innerHTML='';users.slice(0,4).forEach(u=>{const row=document.createElement('div');row.className='suggestion-row';row.innerHTML=`${avatarHtml(u)}<div><strong>${esc(u.displayName)}</strong><span>@${esc(u.username)}</span></div><button class="${u.followed?'following':''}">${u.followed?'Following':'Follow'}</button>`;row.querySelector('.avatar').onclick=row.querySelector('div:nth-child(2)').onclick=()=>loadProfile(u.id);row.querySelector('button').onclick=async e=>{const out=await api(`/users/${u.id}/follow`,{method:'POST'});e.currentTarget.textContent=out.followed?'Following':'Follow';e.currentTarget.classList.toggle('following',out.followed)};box.appendChild(row)});if(!users.length)box.innerHTML='<div class="empty-state">Your community starts here.</div>';$('#communityPulse').textContent=`${stats.people} ${stats.people===1?'person':'people'} · ${stats.posts} ${stats.posts===1?'post':'posts'}`;}catch{}}
  async function loadProfile(id){showOnly('profile');const box=$('#profileContent');box.innerHTML=skeletons();try{const {profile,posts,replies}=await api(`/users/${id}`);if(!profile)throw new Error('Profile not found.');state.currentProfile=profile;box.innerHTML=`<div class="profile-cover" style="--cover:${esc(profile.coverColor||'#6856e8')}"></div><div class="profile-header"><div class="profile-top">${avatarHtml(profile,'avatar profile-avatar')}<button class="btn ${id===state.user.id?'secondary':'primary'} profile-action">${id===state.user.id?'Edit profile':profile.followed?'Following':'Follow'}</button></div><h1>${esc(profile.displayName)}</h1><span class="profile-handle">@${esc(profile.username)}</span><p class="profile-bio">${esc(profile.bio||'No bio yet.')}</p><div class="profile-meta">${profile.location?`<span>${icon('pin')}${esc(profile.location)}</span>`:''}${profile.website?`<a href="${esc(profile.website)}" target="_blank" rel="noreferrer">${icon('link')}${esc(profile.website.replace(/^https?:\/\//,''))}</a>`:''}<span>${icon('calendar')}Joined ${new Intl.DateTimeFormat(undefined,{month:'long',year:'numeric'}).format(new Date(`${profile.createdAt}Z`))}</span></div><div class="profile-stats"><strong>${profile.followingCount||0} <span>Following</span></strong><strong id="profileFollowers">${profile.followerCount||0} <span>Followers</span></strong></div><div class="profile-tabs"><button class="active" data-profile-tab="posts">Posts</button><button data-profile-tab="replies">Replies</button><button data-profile-tab="media">Media</button></div></div><div class="profile-content"></div>`;
    const content=$('.profile-content',box);renderPosts(content,posts,'No posts yet.');$$('[data-profile-tab]',box).forEach(b=>b.onclick=()=>{$$('[data-profile-tab]',box).forEach(x=>x.classList.toggle('active',x===b));if(b.dataset.profileTab==='posts')renderPosts(content,posts,'No posts yet.');if(b.dataset.profileTab==='media')renderPosts(content,posts.filter(p=>p.image),'No media posts yet.');if(b.dataset.profileTab==='replies')content.innerHTML=replies.length?`<div class="profile-replies">${replies.map(r=>`<div class="reply-row"><small>Replied to @${esc(r.postUsername)}</small><p>${esc(r.content)}</p></div>`).join('')}</div>`:empty('No replies yet.')});
    $('.profile-action',box).onclick=id===state.user.id?openProfileEditor:async e=>{const out=await api(`/users/${id}/follow`,{method:'POST'});e.currentTarget.textContent=out.followed?'Following':'Follow';e.currentTarget.className=`btn ${out.followed?'secondary':'primary'} profile-action`;$('#profileFollowers').innerHTML=`${out.followerCount} <span>Followers</span>`;loadSuggestions()};
  }catch(e){box.innerHTML=empty(e.message)}}
  function selectCover(color){const form=$('#profileForm');form.coverColor.value=color;$$('[data-cover-color]',form).forEach(b=>b.classList.toggle('selected',b.dataset.coverColor===color))}
  function openProfileEditor(){const f=$('#profileForm');f.displayName.value=state.user.displayName;f.bio.value=state.user.bio||'';f.location.value=state.user.location||'';f.website.value=state.user.website||'';state.avatarImage='';state.removeAvatar=false;$('#avatarImage').value='';avatar($('#avatarPreview'),state.user);selectCover(state.user.coverColor||'#6856e8');$('.form-status',f).textContent='';$('#profileDialog').showModal()}
  $('[data-close-dialog]').onclick=()=>$('#profileDialog').close();$$('[data-cover-color]').forEach(b=>b.onclick=()=>selectCover(b.dataset.coverColor));$('#avatarImage').onchange=async e=>{try{state.avatarImage=await imageData(e.target.files[0],512);state.removeAvatar=false;avatar($('#avatarPreview'),{...state.user,avatar:state.avatarImage});toast('Photo ready to save')}catch(err){toast(err.message)}};$('#removeAvatar').onclick=()=>{state.avatarImage='';state.removeAvatar=true;avatar($('#avatarPreview'),{...state.user,avatar:''})};$('#profileForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,status=$('.form-status',f),body=formObject(f);body.avatar=state.avatarImage;body.removeAvatar=state.removeAvatar;status.textContent='Saving…';try{const {user}=await api('/profile',{method:'PATCH',body:JSON.stringify(body)});state.user={...state.user,...user};setUser(state.user);$('#profileDialog').close();loadProfile(state.user.id);toast('Profile updated')}catch(err){status.textContent=err.message}};
  async function loadConversations(silent=false){const box=$('#conversationList');if(!silent)box.innerHTML=skeletons();try{const {conversations}=await api('/conversations');box.innerHTML=conversations.length?'':empty('No conversations yet.');conversations.forEach(c=>{const row=document.createElement('div');row.className=`conversation-item ${Number(c.id)===state.activeConversation?'active':''}`;row.dataset.conversationId=c.id;row.innerHTML=`${avatarHtml(c.other)}<div><strong>${esc(c.other?.displayName||'Conversation')}</strong><span>${esc(c.lastMessage||'Start a conversation')}</span></div>`;row.onclick=()=>openConversation(c.id,c.other);box.appendChild(row)})}catch(e){if(!silent)box.innerHTML=empty(e.message)}}
  async function startConversation(userId){try{const {conversation}=await api('/conversations',{method:'POST',body:JSON.stringify({userId})});const {profile}=await api(`/users/${userId}`);showView('messages');openConversation(conversation.id,profile)}catch(e){toast(e.message)}}$('#newConversation').onclick=()=>showView('search');
  function stopMessagePolling(){clearInterval(state.messagePoll);state.messagePoll=null;state.messageRefresh=null;state.activeConversation=null}
  function stopLiveUpdates(){stopMessagePolling();clearInterval(state.conversationPoll);state.conversationPoll=null}
  async function startConversationUpdates(){clearInterval(state.conversationPoll);await loadConversations();state.conversationPoll=setInterval(()=>loadConversations(true),1500)}
  async function openConversation(id,other){stopMessagePolling();state.activeConversation=Number(id);const panel=$('#messagePanel');panel.style.display='flex';panel.innerHTML=`<header class="message-header">${avatarHtml(other)}<strong>${esc(other?.displayName||'Conversation')}</strong></header><div class="message-stream"></div><form class="message-form"><input maxlength="1000" placeholder="Write a message…" required><button aria-label="Send">${icon('send')}</button></form>`;let lastMessageId=0,refreshing=false;const refresh=async(forceScroll=false)=>{if(refreshing||state.activeConversation!==Number(id))return;refreshing=true;try{const {messages}=await api(`/conversations/${id}/messages`),stream=$('.message-stream',panel),latest=Number(messages.at(-1)?.id||0);if(latest!==lastMessageId){const nearBottom=stream.scrollHeight-stream.scrollTop-stream.clientHeight<80;stream.innerHTML=messages.map(m=>`<div class="bubble ${m.senderId===state.user.id?'mine':''}">${esc(m.content)}</div>`).join('');if(forceScroll||nearBottom||!lastMessageId)stream.scrollTop=stream.scrollHeight;lastMessageId=latest}}catch(e){if(forceScroll)toast(e.message)}finally{refreshing=false}};state.messageRefresh=refresh;await refresh(true);$('.message-form',panel).onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,input=$('input',form),button=$('button',form),content=input.value.trim();if(!content||button.disabled)return;button.disabled=true;try{const {message}=await api(`/conversations/${id}/messages`,{method:'POST',body:JSON.stringify({content})});input.value='';const stream=$('.message-stream',panel),bubble=document.createElement('div');bubble.className='bubble mine';bubble.textContent=message.content;stream.appendChild(bubble);stream.scrollTop=stream.scrollHeight;lastMessageId=Number(message.id);const preview=$(`[data-conversation-id="${id}"] span`);if(preview)preview.textContent=message.content}catch(err){toast(err.message)}finally{button.disabled=false;input.focus()}};state.messagePoll=setInterval(()=>refresh(false),750)}
  document.addEventListener('visibilitychange',()=>{if(!document.hidden)state.messageRefresh?.(true)});window.addEventListener('focus',()=>state.messageRefresh?.(true));
  async function loadNotificationBadge(){try{const {notifications}=await api('/notifications');$('#notificationBadge').textContent=notifications.filter(n=>!n.is_read).length||''}catch{}}
  async function loadNotifications(){const box=$('#notificationList');try{const {notifications}=await api('/notifications');box.innerHTML=notifications.length?'':empty('You are all caught up.');notifications.forEach(n=>{const row=document.createElement('div');row.className=`notification-row ${n.is_read?'':'unread'}`;row.innerHTML=`${avatarHtml({avatar:n.actorAvatar,displayName:n.actorName})}<div><p>${esc(n.message)}</p><small>${date(n.created_at)}</small></div>${icon(n.type==='like'?'heart':n.type==='message'?'mail':'comment')}`;box.appendChild(row)})}catch(e){box.innerHTML=empty(e.message)}}$('#markRead').onclick=async()=>{await api('/notifications/read',{method:'POST'});$('#notificationBadge').textContent='';loadNotifications()};
  async function loadAdmin(){if(state.user.role!=='admin')return showView('feed');const box=$('#adminContent');box.innerHTML=skeletons();try{const {stats,users,posts}=await api('/admin/stats');box.innerHTML=`<div class="stats-grid">${Object.entries(stats).map(([k,v])=>`<article class="stat-card"><span>Total ${esc(k)}</span><strong>${v}</strong></article>`).join('')}</div><form class="search-box admin-filter">${icon('search')}<input placeholder="Filter users or posts"></form><h2 class="admin-heading">Accounts</h2><div class="admin-table">${users.map(u=>`<div class="admin-row" data-user-id="${u.id}"><span>${esc(u.displayName)} · @${esc(u.username)}</span><span>${esc(u.role)}${u.suspended?' · suspended':''}</span><div class="admin-actions"><button class="btn secondary compact suspend-user" ${u.id===state.user.id?'disabled':''}>${u.suspended?'Restore':'Suspend'}</button><button class="btn danger compact delete-user" ${u.id===state.user.id?'disabled':''}>Delete</button></div></div>`).join('')}</div><h2 class="admin-heading">Posts</h2><div class="admin-table">${posts.map(p=>`<div class="admin-row" data-post-id="${p.id}"><span>${esc(p.content||'Image post')}</span><span>@${esc(p.username)}</span><button class="btn danger compact delete-post">Delete</button></div>`).join('')}</div>`;$('.admin-filter input').oninput=e=>{$$('.admin-row',box).forEach(r=>r.hidden=!r.innerText.toLowerCase().includes(e.target.value.toLowerCase()))};$$('.suspend-user',box).forEach(b=>b.onclick=async()=>{try{await api(`/admin/users/${b.closest('[data-user-id]').dataset.userId}/suspend`,{method:'POST'});loadAdmin()}catch(e){toast(e.message)}});$$('.delete-user',box).forEach(b=>b.onclick=()=>confirmDelete(async()=>{await api(`/admin/users/${b.closest('[data-user-id]').dataset.userId}`,{method:'DELETE'});toast('Account deleted');loadAdmin()}));$$('.delete-post',box).forEach(b=>b.onclick=()=>confirmDelete(async()=>{await api(`/posts/${b.closest('[data-post-id]').dataset.postId}`,{method:'DELETE'});toast('Post deleted');loadAdmin()}))}catch(e){box.innerHTML=empty(e.message)}}
  bootstrap();
})();
