(() => {
  const visibilityStyle = document.createElement('style');
  visibilityStyle.textContent = '[hidden]{display:none!important}';
  document.head.appendChild(visibilityStyle);
  const apiRoot = `${String(window.__AKIO_API_BASE_URL__ || '').replace(/\/$/,'')}/api/social`;
  const state = { user:null, postImage:'', avatarImage:'', currentProfile:null, activeConversation:null };
  const $ = (s,r=document) => r.querySelector(s); const $$ = (s,r=document) => [...r.querySelectorAll(s)];
  const esc = value => String(value ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const date = value => new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(`${value}Z`));
  function avatar(el,user){el.style.backgroundImage=user?.avatar?`url(${user.avatar})`:'';el.textContent=user?.avatar?'':String(user?.displayName||user?.username||'?')[0].toUpperCase()}
  function avatarHtml(user,cls='avatar'){return `<div class="${cls}"${user?.avatar?` style="background-image:url(${user.avatar})"`:''}>${user?.avatar?'':esc(String(user?.displayName||user?.username||'?')[0].toUpperCase())}</div>`}
  function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2500)}
  async function api(path,options={}){const response=await fetch(`${apiRoot}${path}`,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await response.json().catch(()=>({error:'Invalid server response.'}));if(!response.ok)throw new Error(data.error||'Request failed.');return data}
  function formObject(form){return Object.fromEntries(new FormData(form).entries())}
  async function imageData(file){if(!file)return '';if(file.size>1_500_000)throw new Error('Images must be 1.5 MB or smaller.');if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('Use a PNG, JPEG, or WebP image.');return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Could not read image.'));reader.readAsDataURL(file)})}
  function setUser(user){state.user=user;$('#authView').hidden=!!user;$('#appView').hidden=!user;if(!user)return;$('#sideName').textContent=user.displayName;$('#sideUsername').textContent=`@${user.username}`;avatar($('#sideAvatar'),user);avatar($('#composerAvatar'),user);$('#adminNav').hidden=user.role!=='admin'}
  async function bootstrap(){try{const {user}=await api('/me');setUser(user);if(user){showView('feed');await Promise.all([loadFeed(),loadNotificationBadge()])}}catch{setUser(null)}}
  $$('.auth-tabs button').forEach(button=>button.onclick=()=>{$$('.auth-tabs button').forEach(x=>x.classList.toggle('active',x===button));$('#loginForm').hidden=button.dataset.authTab!=='login';$('#registerForm').hidden=button.dataset.authTab!=='register';$('#authStatus').textContent=''});
  async function authSubmit(form,path){const status=$('#authStatus');status.textContent='';try{const {user}=await api(path,{method:'POST',body:JSON.stringify(formObject(form))});setUser(user);form.reset();showView('feed');await loadFeed()}catch(e){status.textContent=e.message}}
  $('#loginForm').onsubmit=e=>{e.preventDefault();authSubmit(e.currentTarget,'/login')};$('#registerForm').onsubmit=e=>{e.preventDefault();authSubmit(e.currentTarget,'/register')};
  $('#logoutButton').onclick=async()=>{await api('/logout',{method:'POST'});setUser(null)};
  function showView(name){$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$$('.view').forEach(x=>x.hidden=x.id!==`${name}View`);if(name==='feed')loadFeed();if(name==='search')setTimeout(()=>$('#searchForm input').focus(),30);if(name==='messages')loadConversations();if(name==='notifications')loadNotifications();if(name==='profile')loadProfile(state.user.id);if(name==='admin')loadAdmin()}
  $$('[data-view]').forEach(x=>x.onclick=()=>showView(x.dataset.view));$$('[data-compose]').forEach(x=>x.onclick=()=>{showView('feed');$('#postForm textarea').focus()});
  $('#postImage').onchange=async e=>{try{state.postImage=await imageData(e.target.files[0]);$('#postPreview').style.backgroundImage=`url(${state.postImage})`;$('#postPreview').hidden=false}catch(err){toast(err.message);e.target.value=''}};
  $('#postForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,status=$('#postStatus');status.textContent='Posting…';try{await api('/posts',{method:'POST',body:JSON.stringify({content:form.content.value,image:state.postImage})});form.reset();state.postImage='';$('#postPreview').hidden=true;status.textContent='';toast('Post published');await loadFeed()}catch(err){status.textContent=err.message}};
  async function loadFeed(){const list=$('#feedList');list.innerHTML='<div class="empty-state">Loading community posts…</div>';try{const {posts}=await api('/feed');renderPosts(list,posts)}catch(e){list.innerHTML=`<div class="empty-state">${esc(e.message)}</div>`}}
  function renderPosts(container,posts){container.innerHTML=posts.length?'':'<div class="empty-state">No posts yet. Start the conversation.</div>';posts.forEach(post=>container.appendChild(postElement(post)))}
  function postElement(post){const article=document.createElement('article');article.className='post';article.dataset.postId=post.id;const own=post.authorId===state.user.id||state.user.role==='admin';article.innerHTML=`<div class="post-head">${avatarHtml(post)}<div><strong>${esc(post.displayName)} <small>@${esc(post.username)}</small></strong><span>${date(post.createdAt)}</span></div>${own?'<button class="post-menu" title="Delete post">•••</button>':''}</div><p class="post-content">${esc(post.content)}</p>${post.image?`<img class="post-image" src="${post.image}" alt="Photo shared by ${esc(post.displayName)}">`:''}<div class="post-actions"><button class="like ${post.liked?'active':''}">♥ <span>${post.likeCount}</span></button><button class="comment-toggle">◯ <span>${post.commentCount}</span></button><button class="share">↗ Share</button></div><div class="comments" hidden><div class="comment-list"></div><form class="comment-form"><input maxlength="500" placeholder="Write a comment…" required><button>↑</button></form></div>`;
    $('.post-menu',article)?.addEventListener('click',()=>confirmDelete(async()=>{await api(`/posts/${post.id}`,{method:'DELETE'});article.remove();toast('Post deleted')}));
    $('.like',article).onclick=async e=>{const button=e.currentTarget;try{const out=await api(`/posts/${post.id}/like`,{method:'POST'});button.classList.toggle('active',out.liked);$('span',button).textContent=out.count}catch(err){toast(err.message)}};
    $('.share',article).onclick=async()=>{const url=`${location.origin}${location.pathname}#post-${post.id}`;try{await navigator.clipboard.writeText(url);toast('Post link copied')}catch{toast('Copy unavailable')}};
    $('.comment-toggle',article).onclick=()=>toggleComments(article,post.id);
    $('.comment-form',article).onsubmit=async e=>{e.preventDefault();const input=$('input',e.currentTarget);try{await api(`/posts/${post.id}/comments`,{method:'POST',body:JSON.stringify({content:input.value})});input.value='';await loadComments(article,post.id);const count=$('.comment-toggle span',article);count.textContent=Number(count.textContent)+1}catch(err){toast(err.message)}};
    return article
  }
  async function toggleComments(article,id){const section=$('.comments',article);section.hidden=!section.hidden;if(!section.hidden)await loadComments(article,id)}
  async function loadComments(article,id){const list=$('.comment-list',article);const {comments}=await api(`/posts/${id}/comments`);list.innerHTML=comments.map(c=>`<div class="comment" data-comment-id="${c.id}">${avatarHtml(c)}<div><strong>${esc(c.displayName)}</strong><p>${esc(c.content)}</p><small>${date(c.createdAt)}</small></div>${c.userId===state.user.id||state.user.role==='admin'?'<button title="Delete comment">×</button>':''}</div>`).join('');$$('.comment button',list).forEach(button=>button.onclick=()=>confirmDelete(async()=>{await api(`/comments/${button.closest('.comment').dataset.commentId}`,{method:'DELETE'});button.closest('.comment').remove();toast('Comment deleted')}))}
  let confirmAction=null;function confirmDelete(action){confirmAction=action;$('#confirmDialog').showModal()}$('[data-confirm-cancel]').onclick=()=>$('#confirmDialog').close();$('[data-confirm-ok]').onclick=async()=>{try{await confirmAction()}catch(e){toast(e.message)}finally{$('#confirmDialog').close()}};
  let searchTimer;$('#searchForm input').oninput=e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>searchUsers(e.target.value),250)};$('#searchForm').onsubmit=e=>{e.preventDefault();searchUsers(e.currentTarget.q.value)};
  async function searchUsers(q){const box=$('#searchResults');if(!q.trim()){box.className='people-list empty-state';box.textContent='Search for someone to connect with.';return}box.className='people-list';const {users}=await api(`/search?q=${encodeURIComponent(q)}`);box.innerHTML=users.length?'':'<div class="empty-state">No people found.</div>';users.forEach(user=>{const row=document.createElement('div');row.className='person-row';row.innerHTML=`${avatarHtml(user)}<div><strong>${esc(user.displayName)}</strong><span>@${esc(user.username)} · ${esc(user.bio||'New to Loopline')}</span></div><div><button class="profile-button">Profile</button> <button class="message-button">Message</button></div>`;$('.profile-button',row).onclick=()=>loadProfile(user.id);$('.message-button',row).onclick=()=>startConversation(user.id);box.appendChild(row)})}
  async function loadProfile(id){showViewOnly('profile');const content=$('#profileContent');content.innerHTML='<div class="empty-state">Loading profile…</div>';try{const {profile,posts}=await api(`/users/${id}`);if(!profile)throw new Error('Profile not found.');state.currentProfile=profile;content.innerHTML=`<div class="profile-cover"></div><div class="profile-header"><div class="profile-top">${avatarHtml(profile,'avatar profile-avatar')}<button>${id===state.user.id?'Edit profile':'Message'}</button></div><h1>${esc(profile.displayName)}</h1><span>@${esc(profile.username)}</span><p>${esc(profile.bio||'No bio yet.')}</p><div class="profile-meta">Joined ${new Intl.DateTimeFormat(undefined,{month:'long',year:'numeric'}).format(new Date(`${profile.createdAt}Z`))}</div></div><div class="profile-posts"></div>`;$('.profile-top button',content).onclick=id===state.user.id?openProfileEditor:()=>startConversation(id);renderPosts($('.profile-posts',content),posts)}catch(e){content.innerHTML=`<div class="empty-state">${esc(e.message)}</div>`}}
  function showViewOnly(name){$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$$('.view').forEach(x=>x.hidden=x.id!==`${name}View`)}
  function openProfileEditor(){$('#profileForm').displayName.value=state.user.displayName;$('#profileForm').bio.value=state.user.bio||'';state.avatarImage='';$('#avatarPreview').hidden=true;$('#profileDialog').showModal()}$('[data-close-dialog]').onclick=()=>$('#profileDialog').close();
  $('#avatarImage').onchange=async e=>{try{state.avatarImage=await imageData(e.target.files[0]);$('#avatarPreview').style.backgroundImage=`url(${state.avatarImage})`;$('#avatarPreview').hidden=false}catch(err){toast(err.message)}};
  $('#profileForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,status=$('.form-status',form);try{const b=formObject(form);b.avatar=state.avatarImage;const {user}=await api('/profile',{method:'PATCH',body:JSON.stringify(b)});state.user={...state.user,...user};setUser(state.user);$('#profileDialog').close();loadProfile(state.user.id);toast('Profile updated')}catch(err){status.textContent=err.message}};
  async function loadConversations(){const list=$('#conversationList');list.innerHTML='<div class="empty-state">Loading…</div>';try{const {conversations}=await api('/conversations');list.innerHTML=conversations.length?'':'<div class="empty-state">No conversations yet.</div>';conversations.forEach(c=>{const row=document.createElement('div');row.className='conversation-item';row.innerHTML=`${avatarHtml(c.other)}<div><strong>${esc(c.other?.displayName||'Conversation')}</strong><span>${esc(c.lastMessage||'Start a conversation')}</span></div>`;row.onclick=()=>openConversation(c.id,c.other);list.appendChild(row)})}catch(e){list.innerHTML=`<div class="empty-state">${esc(e.message)}</div>`}}
  async function startConversation(userId){try{const {conversation}=await api('/conversations',{method:'POST',body:JSON.stringify({userId})});const {profile}=await api(`/users/${userId}`);showView('messages');openConversation(conversation.id,profile)}catch(e){toast(e.message)}}
  async function openConversation(id,other){state.activeConversation=id;const panel=$('#messagePanel');panel.innerHTML=`<header class="message-header">${avatarHtml(other)}<strong>${esc(other?.displayName||'Conversation')}</strong></header><div class="message-stream"></div><form class="message-form"><input maxlength="1000" placeholder="Write a message…" required><button>↑</button></form>`;async function refresh(){const {messages}=await api(`/conversations/${id}/messages`);const stream=$('.message-stream',panel);stream.innerHTML=messages.map(m=>`<div class="bubble ${m.senderId===state.user.id?'mine':''}">${esc(m.content)}</div>`).join('');stream.scrollTop=stream.scrollHeight}await refresh();$('.message-form',panel).onsubmit=async e=>{e.preventDefault();const input=$('input',e.currentTarget);try{await api(`/conversations/${id}/messages`,{method:'POST',body:JSON.stringify({content:input.value})});input.value='';await refresh()}catch(err){toast(err.message)}}}
  $('#newConversation').onclick=()=>showView('search');
  async function loadNotificationBadge(){try{const {notifications}=await api('/notifications');const count=notifications.filter(n=>!n.is_read).length;$('#notificationBadge').textContent=count||''}catch{}}
  async function loadNotifications(){const list=$('#notificationList');const {notifications}=await api('/notifications');list.innerHTML=notifications.length?'':'<div class="empty-state">No notifications yet.</div>';notifications.forEach(n=>{const row=document.createElement('div');row.className=`notification-row ${n.is_read?'':'unread'}`;row.innerHTML=`${avatarHtml({avatar:n.actorAvatar,displayName:n.actorName})}<div><p>${esc(n.message)}</p><small>${date(n.created_at)}</small></div><span>${n.type==='like'?'♥':n.type==='message'?'✉':'◯'}</span>`;list.appendChild(row)})}
  $('#markRead').onclick=async()=>{await api('/notifications/read',{method:'POST'});$('#notificationBadge').textContent='';loadNotifications()};
  async function loadAdmin(){
    if(state.user.role!=='admin')return showView('feed');
    const box=$('#adminContent');box.innerHTML='<div class="empty-state">Loading dashboard…</div>';
    try{
      const {stats,users,posts}=await api('/admin/stats');
      box.innerHTML=`<div class="stats-grid">${Object.entries(stats).map(([k,v])=>`<article class="stat-card"><span>Total ${esc(k)}</span><strong>${v}</strong></article>`).join('')}</div><form class="search-box admin-filter"><span>⌕</span><input placeholder="Filter users or posts" autocomplete="off"></form><div class="admin-table"><div class="admin-row"><strong>User</strong><strong>Role</strong><strong>Action</strong></div>${users.map(u=>`<div class="admin-row" data-user-id="${u.id}"><span>${esc(u.displayName)} · @${esc(u.username)}</span><span>${esc(u.role)}${u.suspended?' · suspended':''}</span><button ${u.id===state.user.id?'disabled':''}>${u.suspended?'Restore':'Suspend'}</button></div>`).join('')}</div><div class="admin-table admin-posts"><div class="admin-row"><strong>Recent post</strong><strong>Author</strong><strong>Action</strong></div>${posts.map(p=>`<div class="admin-row" data-post-id="${p.id}"><span>${esc(p.content||'Image post')}</span><span>@${esc(p.username)}</span><button class="danger">Delete</button></div>`).join('')}</div>`;
      $('.admin-filter input',box).oninput=e=>{$$('.admin-row[data-user-id],.admin-row[data-post-id]',box).forEach(row=>row.hidden=!row.innerText.toLowerCase().includes(e.target.value.toLowerCase()))};
      $$('.admin-row[data-user-id] button',box).forEach(button=>button.onclick=async()=>{try{await api(`/admin/users/${button.closest('.admin-row').dataset.userId}/suspend`,{method:'POST'});loadAdmin();toast('User status updated')}catch(e){toast(e.message)}});
      $$('.admin-row[data-post-id] button',box).forEach(button=>button.onclick=()=>confirmDelete(async()=>{await api(`/posts/${button.closest('.admin-row').dataset.postId}`,{method:'DELETE'});loadAdmin();toast('Post removed by moderator')}));
    }catch(e){box.innerHTML=`<div class="empty-state">${esc(e.message)}</div>`}
  }
  bootstrap();
})();
