import { DatabaseSync } from 'node:sqlite';
import { mkdirSync } from 'node:fs';
import path from 'node:path';
import { randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
import { createSocialAi } from './social-ai.mjs';

const dataDir = process.env.SOCIAL_DATA_DIR || path.join(process.cwd(), 'data');
mkdirSync(dataDir, { recursive: true });
const db = new DatabaseSync(path.join(dataDir, 'social.sqlite'));
const ownerEmail = (process.env.SOCIAL_ADMIN_EMAIL || 'azsalomon69@gmail.com').trim().toLowerCase();
db.exec(`PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY, username TEXT UNIQUE COLLATE NOCASE, email TEXT UNIQUE COLLATE NOCASE, password_hash TEXT NOT NULL, display_name TEXT NOT NULL, bio TEXT DEFAULT '', avatar TEXT DEFAULT '', role TEXT NOT NULL DEFAULT 'user' CHECK(role IN ('user','admin')), suspended INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS posts(id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, content TEXT NOT NULL DEFAULT '', image TEXT DEFAULT '', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS likes(user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id,post_id));
CREATE TABLE IF NOT EXISTS bookmarks(user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id,post_id));
CREATE TABLE IF NOT EXISTS follows(follower_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, following_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(follower_id,following_id), CHECK(follower_id!=following_id));
CREATE TABLE IF NOT EXISTS comments(id INTEGER PRIMARY KEY, post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, content TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS conversations(id INTEGER PRIMARY KEY, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS conversation_members(conversation_id INTEGER REFERENCES conversations(id) ON DELETE CASCADE, user_id INTEGER REFERENCES users(id) ON DELETE CASCADE, PRIMARY KEY(conversation_id,user_id));
CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY, conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE, sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, content TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, actor_id INTEGER REFERENCES users(id) ON DELETE CASCADE, type TEXT NOT NULL, post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE, message TEXT NOT NULL, is_read INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS typing_status(conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(conversation_id,user_id));
CREATE TABLE IF NOT EXISTS moderation_log(id INTEGER PRIMARY KEY, admin_id INTEGER NOT NULL REFERENCES users(id), action TEXT NOT NULL, target_type TEXT NOT NULL, target_id INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username); CREATE INDEX IF NOT EXISTS idx_posts_created ON posts(created_at DESC); CREATE INDEX IF NOT EXISTS idx_comments_post ON comments(post_id); CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id,created_at);`);
if (!db.prepare("PRAGMA table_info(users)").all().some(column => column.name === 'cover_color')) {
  db.exec("ALTER TABLE users ADD COLUMN cover_color TEXT NOT NULL DEFAULT '#6856e8'");
}
if (!db.prepare("PRAGMA table_info(users)").all().some(column => column.name === 'location')) db.exec("ALTER TABLE users ADD COLUMN location TEXT NOT NULL DEFAULT ''");
if (!db.prepare("PRAGMA table_info(users)").all().some(column => column.name === 'website')) db.exec("ALTER TABLE users ADD COLUMN website TEXT NOT NULL DEFAULT ''");
if (!db.prepare("PRAGMA table_info(users)").all().some(column => column.name === 'last_seen_at')) db.exec("ALTER TABLE users ADD COLUMN last_seen_at TEXT");
if (!db.prepare("PRAGMA table_info(users)").all().some(column => column.name === 'is_ai')) db.exec("ALTER TABLE users ADD COLUMN is_ai INTEGER NOT NULL DEFAULT 0");
if (!db.prepare("PRAGMA table_info(comments)").all().some(column => column.name === 'parent_comment_id')) db.exec("ALTER TABLE comments ADD COLUMN parent_comment_id INTEGER REFERENCES comments(id) ON DELETE CASCADE");
if (!db.prepare("PRAGMA table_info(notifications)").all().some(column => column.name === 'conversation_id')) db.exec("ALTER TABLE notifications ADD COLUMN conversation_id INTEGER REFERENCES conversations(id) ON DELETE CASCADE");
// Keep the portfolio owner as an administrator even when the account existed
// before SOCIAL_ADMIN_EMAIL was configured on the host.
if (ownerEmail) db.prepare("UPDATE users SET role='admin', suspended=0 WHERE lower(email)=?").run(ownerEmail);

const attempts = new Map();
const coverColors = new Set(['#6856e8','#e84d8a','#ef8b2c','#159b83','#2774e6','#263044']);
function headers(request) {
  const origin = request.headers.get('origin');
  const configured = [process.env.FRONTEND_URL, ...(process.env.ALLOWED_ORIGINS || '').split(',')].filter(Boolean).map(x => x.trim().replace(/\/$/,''));
  const allowed = !origin || /^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(origin) || configured.includes(origin.replace(/\/$/,''));
  if (!allowed) return null;
  return {'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Access-Control-Allow-Origin':origin || '*','Access-Control-Allow-Credentials':'true','Access-Control-Allow-Methods':'GET,POST,PATCH,DELETE,OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Vary':'Origin'};
}
function json(request, data, status=200, extra={}) { const h=headers(request); if(!h) return Response.json({error:'Origin not allowed.'},{status:403}); return Response.json(data,{status,headers:{...h,...extra}}); }
function clean(value,max=500){return String(value||'').trim().slice(0,max)}
function hashPassword(password){const salt=randomBytes(16).toString('hex');return `${salt}:${scryptSync(password,salt,64).toString('hex')}`}
function verifyPassword(password,stored){try{const [salt,key]=stored.split(':');return timingSafeEqual(Buffer.from(key,'hex'),scryptSync(password,salt,64))}catch{return false}}
function cookie(request,name){return request.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(`${name}=`))?.slice(name.length+1) || ''}
function sessionToken(request){const auth=request.headers.get('authorization')||'';const bearer=/^Bearer\s+([a-f0-9]{64})$/i.exec(auth);return bearer?.[1]||cookie(request,'social_session')}
function sessionUser(request){const token=sessionToken(request);if(!token)return null;return db.prepare(`SELECT u.id,u.username,u.email,u.display_name displayName,u.bio,u.avatar,u.cover_color coverColor,u.location,u.website,u.role,u.suspended,u.is_ai isAi,u.created_at createdAt FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>datetime('now')`).get(token)||null}
function requireUser(request){const user=sessionUser(request);if(!user)throw Object.assign(new Error('Please log in.'),{status:401});if(user.suspended)throw Object.assign(new Error('This account is suspended.'),{status:403});db.prepare("UPDATE users SET last_seen_at=CURRENT_TIMESTAMP WHERE id=? AND (last_seen_at IS NULL OR last_seen_at<datetime('now','-10 seconds'))").run(user.id);return user}
function requireAdmin(request){const user=requireUser(request);if(user.role!=='admin')throw Object.assign(new Error('Administrator access required.'),{status:403});return user}
function validImage(value){if(!value)return '';const match=/^data:(image\/(?:png|jpeg|webp));base64,([A-Za-z0-9+/=]+)$/.exec(value);if(!match)throw Object.assign(new Error('Use a PNG, JPEG, or WebP image.'),{status:400});const bytes=Buffer.from(match[2],'base64');if(bytes.length>1_500_000)throw Object.assign(new Error('Images must be 1.5 MB or smaller.'),{status:400});const ok=(match[1]==='image/png'&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))||(match[1]==='image/jpeg'&&bytes[0]===255&&bytes[1]===216)||(match[1]==='image/webp'&&bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP');if(!ok)throw Object.assign(new Error('The uploaded file is not a valid image.'),{status:400});return value}
function validAvatar(value){if(!value)return '';if(!/^preset:(?:[1-9]|10)$/.test(value))throw Object.assign(new Error('Choose one of the available profile characters.'),{status:400});return value}
async function body(request){try{return await request.json()}catch{throw Object.assign(new Error('Invalid request body.'),{status:400})}}
function notify(userId,actorId,type,postId,message,conversationId=null){if(userId===actorId)return;db.prepare('INSERT INTO notifications(user_id,actor_id,type,post_id,message,conversation_id) VALUES(?,?,?,?,?,?)').run(userId,actorId,type,postId||null,message,conversationId)}
const socialAi=createSocialAi({db,hashPassword,notify});
socialAi.seed();
socialAi.start();
function publicUser(id){return db.prepare(`SELECT id,username,display_name displayName,bio,avatar,cover_color coverColor,location,website,is_ai isAi,created_at createdAt,(SELECT count(*) FROM follows WHERE following_id=users.id) followerCount,(SELECT count(*) FROM follows WHERE follower_id=users.id) followingCount FROM users WHERE id=?`).get(id)}
function privateUser(id){return db.prepare(`SELECT id,username,email,display_name displayName,bio,avatar,cover_color coverColor,location,website,role,suspended,is_ai isAi,created_at createdAt,(SELECT count(*) FROM follows WHERE following_id=users.id) followerCount,(SELECT count(*) FROM follows WHERE follower_id=users.id) followingCount FROM users WHERE id=?`).get(id)}
function postRows(userId,where='',params=[]){return db.prepare(`SELECT p.id,p.content,p.image,p.created_at createdAt,u.id authorId,u.username,u.display_name displayName,u.avatar,u.is_ai isAi,(SELECT count(*) FROM likes WHERE post_id=p.id) likeCount,(SELECT count(*) FROM comments WHERE post_id=p.id) commentCount,EXISTS(SELECT 1 FROM likes WHERE post_id=p.id AND user_id=?) liked,EXISTS(SELECT 1 FROM bookmarks WHERE post_id=p.id AND user_id=?) bookmarked FROM posts p JOIN users u ON u.id=p.user_id WHERE u.suspended=0 ${where} ORDER BY p.created_at DESC LIMIT 100`).all(userId,userId,...params)}

async function route(request){
  if(request.method==='OPTIONS')return new Response(null,{status:204,headers:headers(request)||{}});
  const url=new URL(request.url);const p=url.pathname.replace(/^\/api\/social/,'')||'/';
  if(p==='/register'&&request.method==='POST'){const b=await body(request);const username=clean(b.username,24);const email=clean(b.email,120).toLowerCase();const displayName=clean(b.displayName,50);const password=String(b.password||'');const avatar=validAvatar(b.avatar||'preset:1');if(!/^[a-zA-Z0-9_]{3,24}$/.test(username))return json(request,{error:'Username must be 3–24 letters, numbers, or underscores.'},400);if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))return json(request,{error:'Enter a valid email address.'},400);if(password.length<8)return json(request,{error:'Password must be at least 8 characters.'},400);if(!displayName)return json(request,{error:'Display name is required.'},400);try{const role=ownerEmail===email?'admin':'user';const result=db.prepare('INSERT INTO users(username,email,password_hash,display_name,avatar,role) VALUES(?,?,?,?,?,?)').run(username,email,hashPassword(password),displayName,avatar,role);return login(request,result.lastInsertRowid)}catch(e){return json(request,{error:'That username or email is already registered.'},409)}}
  if(p==='/login'&&request.method==='POST'){const key=request.headers.get('x-forwarded-for')||'local';const bucket=attempts.get(key)||{count:0,time:Date.now()};if(Date.now()-bucket.time>600000){bucket.count=0;bucket.time=Date.now()}if(bucket.count>=15)return json(request,{error:'Too many login attempts. Try again later.'},429);const b=await body(request);const user=db.prepare('SELECT * FROM users WHERE email=? OR username=?').get(clean(b.login,120),clean(b.login,120));if(!user||!verifyPassword(String(b.password||''),user.password_hash)){bucket.count++;attempts.set(key,bucket);return json(request,{error:'Incorrect username/email or password.'},401)}if(user.suspended)return json(request,{error:'This account is suspended.'},403);attempts.delete(key);return login(request,user.id)}
  if(p==='/logout'&&request.method==='POST'){db.prepare('DELETE FROM sessions WHERE token=?').run(sessionToken(request));const origin=request.headers.get('origin'),cross=origin&&new URL(origin).origin!==new URL(request.url).origin;return json(request,{ok:true},200,{'Set-Cookie':`social_session=; Path=/; HttpOnly; Max-Age=0${cross?'; SameSite=None; Secure':'; SameSite=Lax'}`})}
  if(p==='/me'&&request.method==='GET'){const user=sessionUser(request);return json(request,{user})}
  const user=requireUser(request);
  if(p==='/presence'&&request.method==='POST'){db.prepare('UPDATE users SET last_seen_at=CURRENT_TIMESTAMP WHERE id=?').run(user.id);return json(request,{ok:true})}
  if(p==='/profile'&&request.method==='PATCH'){const b=await body(request);const displayName=clean(b.displayName,50),bio=clean(b.bio,180),location=clean(b.location,60),website=clean(b.website,160),avatar=validAvatar(b.avatar||''),coverColor=coverColors.has(b.coverColor)?b.coverColor:'#6856e8';if(!displayName)return json(request,{error:'Display name is required.'},400);if(website&&!/^https?:\/\/[^\s]+$/i.test(website))return json(request,{error:'Website must begin with http:// or https://.'},400);const nextAvatar=avatar||user.avatar;db.prepare('UPDATE users SET display_name=?,bio=?,avatar=?,cover_color=?,location=?,website=? WHERE id=?').run(displayName,bio,nextAvatar,coverColor,location,website,user.id);return json(request,{user:privateUser(user.id)})}
  if(p==='/feed'&&request.method==='GET')return json(request,{posts:postRows(user.id)});
  if(p==='/posts'&&request.method==='POST'){const b=await body(request);const content=clean(b.content,1000),image=validImage(b.image||'');if(!content&&!image)return json(request,{error:'Write something or add an image.'},400);const out=db.prepare('INSERT INTO posts(user_id,content,image) VALUES(?,?,?)').run(user.id,content,image);socialAi.enqueueForPost({postId:Number(out.lastInsertRowid),actorId:user.id});return json(request,{post:postRows(user.id,'AND p.id=?',[out.lastInsertRowid])[0]},201)}
  let m=p.match(/^\/posts\/(\d+)$/);if(m&&request.method==='DELETE'){const post=db.prepare('SELECT user_id FROM posts WHERE id=?').get(m[1]);if(!post)return json(request,{error:'Post not found.'},404);if(post.user_id!==user.id&&user.role!=='admin')return json(request,{error:'You cannot delete this post.'},403);db.prepare('DELETE FROM posts WHERE id=?').run(m[1]);if(user.role==='admin'&&post.user_id!==user.id)db.prepare('INSERT INTO moderation_log(admin_id,action,target_type,target_id) VALUES(?,?,?,?)').run(user.id,'delete','post',m[1]);return json(request,{ok:true})}
  m=p.match(/^\/posts\/(\d+)\/like$/);if(m&&request.method==='POST'){const post=db.prepare('SELECT user_id FROM posts WHERE id=?').get(m[1]);if(!post)return json(request,{error:'Post not found.'},404);const existing=db.prepare('SELECT 1 FROM likes WHERE user_id=? AND post_id=?').get(user.id,m[1]);if(existing)db.prepare('DELETE FROM likes WHERE user_id=? AND post_id=?').run(user.id,m[1]);else{db.prepare('INSERT INTO likes(user_id,post_id) VALUES(?,?)').run(user.id,m[1]);notify(post.user_id,user.id,'like',Number(m[1]),`${user.displayName} liked your post.`)}return json(request,{liked:!existing,count:db.prepare('SELECT count(*) count FROM likes WHERE post_id=?').get(m[1]).count})}
  m=p.match(/^\/posts\/(\d+)\/bookmark$/);if(m&&request.method==='POST'){if(!db.prepare('SELECT 1 FROM posts WHERE id=?').get(m[1]))return json(request,{error:'Post not found.'},404);const existing=db.prepare('SELECT 1 FROM bookmarks WHERE user_id=? AND post_id=?').get(user.id,m[1]);if(existing)db.prepare('DELETE FROM bookmarks WHERE user_id=? AND post_id=?').run(user.id,m[1]);else db.prepare('INSERT INTO bookmarks(user_id,post_id) VALUES(?,?)').run(user.id,m[1]);return json(request,{bookmarked:!existing})}
  if(p==='/bookmarks'&&request.method==='GET')return json(request,{posts:postRows(user.id,'AND EXISTS(SELECT 1 FROM bookmarks b WHERE b.post_id=p.id AND b.user_id=?)',[user.id])});
  m=p.match(/^\/posts\/(\d+)\/comments$/);if(m&&request.method==='GET'){return json(request,{comments:db.prepare(`SELECT c.id,c.content,c.parent_comment_id parentCommentId,c.created_at createdAt,u.id userId,u.username,u.display_name displayName,u.avatar,u.is_ai isAi,pu.username replyingTo FROM comments c JOIN users u ON u.id=c.user_id LEFT JOIN comments pc ON pc.id=c.parent_comment_id LEFT JOIN users pu ON pu.id=pc.user_id WHERE c.post_id=? ORDER BY c.created_at`).all(m[1])})}
  if(m&&request.method==='POST'){const b=await body(request),content=clean(b.content,500),parentCommentId=Number(b.parentCommentId)||null;if(!content)return json(request,{error:'Comment cannot be empty.'},400);const post=db.prepare('SELECT user_id FROM posts WHERE id=?').get(m[1]);if(!post)return json(request,{error:'Post not found.'},404);let parent=null;if(parentCommentId){parent=db.prepare('SELECT id,user_id FROM comments WHERE id=? AND post_id=?').get(parentCommentId,m[1]);if(!parent)return json(request,{error:'The comment you are replying to was not found.'},404)}const out=db.prepare('INSERT INTO comments(post_id,user_id,content,parent_comment_id) VALUES(?,?,?,?)').run(m[1],user.id,content,parentCommentId);notify(post.user_id,user.id,'comment',Number(m[1]),`${user.displayName} commented on your post.`);if(parent&&parent.user_id!==post.user_id)notify(parent.user_id,user.id,'comment',Number(m[1]),`${user.displayName} replied to your comment.`);socialAi.enqueueForComment({commentId:Number(out.lastInsertRowid),postId:Number(m[1]),actorId:user.id,parentCommentId});return json(request,{comment:db.prepare(`SELECT c.id,c.content,c.parent_comment_id parentCommentId,c.created_at createdAt,u.id userId,u.username,u.display_name displayName,u.avatar,u.is_ai isAi,pu.username replyingTo FROM comments c JOIN users u ON u.id=c.user_id LEFT JOIN comments pc ON pc.id=c.parent_comment_id LEFT JOIN users pu ON pu.id=pc.user_id WHERE c.id=?`).get(out.lastInsertRowid)},201)}
  m=p.match(/^\/comments\/(\d+)$/);if(m&&request.method==='DELETE'){const c=db.prepare('SELECT user_id FROM comments WHERE id=?').get(m[1]);if(!c)return json(request,{error:'Comment not found.'},404);if(c.user_id!==user.id&&user.role!=='admin')return json(request,{error:'You cannot delete this comment.'},403);db.prepare('DELETE FROM comments WHERE id=?').run(m[1]);if(user.role==='admin'&&c.user_id!==user.id)db.prepare('INSERT INTO moderation_log(admin_id,action,target_type,target_id) VALUES(?,?,?,?)').run(user.id,'delete','comment',m[1]);return json(request,{ok:true})}
  if(p==='/search'&&request.method==='GET'){const q=clean(url.searchParams.get('q'),40);if(!q)return json(request,{users:[]});return json(request,{users:db.prepare("SELECT id,username,display_name displayName,bio,avatar,cover_color coverColor,is_ai isAi,created_at createdAt FROM users WHERE suspended=0 AND (username LIKE ? OR display_name LIKE ?) LIMIT 30").all(`%${q}%`,`%${q}%`)})}
  if(p==='/suggestions'&&request.method==='GET'){const users=db.prepare('SELECT id,username,display_name displayName,bio,avatar,cover_color coverColor,is_ai isAi,created_at createdAt,EXISTS(SELECT 1 FROM follows WHERE follower_id=? AND following_id=users.id) followed FROM users WHERE suspended=0 AND id!=? ORDER BY created_at DESC LIMIT 6').all(user.id,user.id);const stats={people:db.prepare('SELECT count(*) n FROM users WHERE suspended=0').get().n,posts:db.prepare('SELECT count(*) n FROM posts').get().n};return json(request,{users,stats})}
  m=p.match(/^\/users\/(\d+)$/);if(m&&request.method==='GET'){const profile=publicUser(m[1]);if(profile)profile.followed=!!db.prepare('SELECT 1 FROM follows WHERE follower_id=? AND following_id=?').get(user.id,m[1]);const replies=db.prepare('SELECT c.id,c.content,c.created_at createdAt,p.id postId,u.username postUsername FROM comments c JOIN posts p ON p.id=c.post_id JOIN users u ON u.id=p.user_id WHERE c.user_id=? ORDER BY c.created_at DESC LIMIT 100').all(m[1]);return json(request,{profile,posts:postRows(user.id,'AND p.user_id=?',[m[1]]),replies})}
  m=p.match(/^\/users\/(\d+)\/follow$/);if(m&&request.method==='POST'){const other=Number(m[1]);if(!other||other===user.id||!publicUser(other))return json(request,{error:'Choose another valid user.'},400);const existing=db.prepare('SELECT 1 FROM follows WHERE follower_id=? AND following_id=?').get(user.id,other);if(existing)db.prepare('DELETE FROM follows WHERE follower_id=? AND following_id=?').run(user.id,other);else db.prepare('INSERT INTO follows(follower_id,following_id) VALUES(?,?)').run(user.id,other);return json(request,{followed:!existing,followerCount:db.prepare('SELECT count(*) n FROM follows WHERE following_id=?').get(other).n})}
  if(p==='/conversations'&&request.method==='GET'){return json(request,{conversations:db.prepare(`SELECT c.id,(SELECT json_object('id',u.id,'username',u.username,'displayName',u.display_name,'avatar',u.avatar,'isAi',u.is_ai,'online',u.last_seen_at>=datetime('now','-35 seconds')) FROM conversation_members cm2 JOIN users u ON u.id=cm2.user_id WHERE cm2.conversation_id=c.id AND u.id!=? LIMIT 1) other,(SELECT content FROM messages WHERE conversation_id=c.id ORDER BY id DESC LIMIT 1) lastMessage,(SELECT created_at FROM messages WHERE conversation_id=c.id ORDER BY id DESC LIMIT 1) updatedAt FROM conversations c JOIN conversation_members cm ON cm.conversation_id=c.id WHERE cm.user_id=? ORDER BY updatedAt DESC`).all(user.id,user.id).map(x=>({...x,other:JSON.parse(x.other||'null')}))})}
  if(p==='/conversations'&&request.method==='POST'){const b=await body(request),other=Number(b.userId);if(!other||other===user.id||!publicUser(other))return json(request,{error:'Choose another valid user.'},400);let convo=db.prepare(`SELECT cm.conversation_id id FROM conversation_members cm JOIN conversation_members cm2 ON cm2.conversation_id=cm.conversation_id WHERE cm.user_id=? AND cm2.user_id=? AND (SELECT count(*) FROM conversation_members WHERE conversation_id=cm.conversation_id)=2`).get(user.id,other);if(!convo){const out=db.prepare('INSERT INTO conversations DEFAULT VALUES').run();db.prepare('INSERT INTO conversation_members(conversation_id,user_id) VALUES(?,?),(?,?)').run(out.lastInsertRowid,user.id,out.lastInsertRowid,other);convo={id:Number(out.lastInsertRowid)}}return json(request,{conversation:convo},201)}
  m=p.match(/^\/conversations\/(\d+)\/messages$/);if(m){const member=db.prepare('SELECT 1 FROM conversation_members WHERE conversation_id=? AND user_id=?').get(m[1],user.id);if(!member)return json(request,{error:'Conversation not found.'},404);if(request.method==='GET'){const other=db.prepare("SELECT u.id,u.is_ai isAi,u.last_seen_at>=datetime('now','-35 seconds') online,EXISTS(SELECT 1 FROM typing_status t WHERE t.conversation_id=? AND t.user_id=u.id AND t.updated_at>=datetime('now','-8 seconds')) typing FROM conversation_members cm JOIN users u ON u.id=cm.user_id WHERE cm.conversation_id=? AND u.id!=?").get(m[1],m[1],user.id);return json(request,{messages:db.prepare('SELECT m.id,m.content,m.created_at createdAt,m.sender_id senderId,u.display_name displayName,u.avatar,u.is_ai isAi FROM messages m JOIN users u ON u.id=m.sender_id WHERE conversation_id=? ORDER BY m.id').all(m[1]),presence:{online:!!other?.online,typing:!!other?.typing,isAi:!!other?.isAi}})}if(request.method==='POST'){const b=await body(request),content=clean(b.content,1000);if(!content)return json(request,{error:'Message cannot be empty.'},400);const out=db.prepare('INSERT INTO messages(conversation_id,sender_id,content) VALUES(?,?,?)').run(m[1],user.id,content);db.prepare('DELETE FROM typing_status WHERE conversation_id=? AND user_id=?').run(m[1],user.id);const recipient=db.prepare('SELECT user_id FROM conversation_members WHERE conversation_id=? AND user_id!=?').get(m[1],user.id);if(recipient){notify(recipient.user_id,user.id,'message',null,`${user.displayName} sent you a message.`,Number(m[1]));socialAi.enqueueForMessage({messageId:Number(out.lastInsertRowid),conversationId:Number(m[1]),actorId:user.id,recipientId:recipient.user_id})}return json(request,{message:db.prepare('SELECT id,content,created_at createdAt,sender_id senderId FROM messages WHERE id=?').get(out.lastInsertRowid)},201)}}
  m=p.match(/^\/conversations\/(\d+)\/typing$/);if(m&&request.method==='POST'){const member=db.prepare('SELECT 1 FROM conversation_members WHERE conversation_id=? AND user_id=?').get(m[1],user.id);if(!member)return json(request,{error:'Conversation not found.'},404);const b=await body(request);if(b.typing)db.prepare("INSERT INTO typing_status(conversation_id,user_id,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(conversation_id,user_id) DO UPDATE SET updated_at=CURRENT_TIMESTAMP").run(m[1],user.id);else db.prepare('DELETE FROM typing_status WHERE conversation_id=? AND user_id=?').run(m[1],user.id);return json(request,{ok:true})}
  if(p==='/notifications'&&request.method==='GET')return json(request,{notifications:db.prepare('SELECT n.*,u.display_name actorName,u.avatar actorAvatar FROM notifications n LEFT JOIN users u ON u.id=n.actor_id WHERE n.user_id=? ORDER BY n.id DESC LIMIT 50').all(user.id)});
  if(p==='/notifications/read'&&request.method==='POST'){db.prepare('UPDATE notifications SET is_read=1 WHERE user_id=?').run(user.id);return json(request,{ok:true})}
  m=p.match(/^\/notifications\/(\d+)\/read$/);if(m&&request.method==='POST'){db.prepare('UPDATE notifications SET is_read=1 WHERE id=? AND user_id=?').run(m[1],user.id);return json(request,{ok:true})}
  if(p==='/admin/stats'&&request.method==='GET'){requireAdmin(request);return json(request,{stats:{users:db.prepare('SELECT count(*) n FROM users').get().n,posts:db.prepare('SELECT count(*) n FROM posts').get().n,comments:db.prepare('SELECT count(*) n FROM comments').get().n,likes:db.prepare('SELECT count(*) n FROM likes').get().n},users:db.prepare('SELECT id,username,email,display_name displayName,role,suspended,created_at createdAt FROM users ORDER BY created_at DESC').all(),posts:postRows(user.id)})}
  m=p.match(/^\/admin\/users\/(\d+)\/suspend$/);if(m&&request.method==='POST'){const admin=requireAdmin(request);if(Number(m[1])===admin.id)return json(request,{error:'You cannot suspend your own account.'},400);const target=db.prepare('SELECT suspended FROM users WHERE id=?').get(m[1]);if(!target)return json(request,{error:'User not found.'},404);db.prepare('UPDATE users SET suspended=? WHERE id=?').run(target.suspended?0:1,m[1]);db.prepare('INSERT INTO moderation_log(admin_id,action,target_type,target_id) VALUES(?,?,?,?)').run(admin.id,target.suspended?'unsuspend':'suspend','user',m[1]);return json(request,{suspended:!target.suspended})}
  m=p.match(/^\/admin\/users\/(\d+)$/);if(m&&request.method==='DELETE'){const admin=requireAdmin(request),targetId=Number(m[1]);if(targetId===admin.id)return json(request,{error:'You cannot delete your own administrator account.'},400);const target=db.prepare('SELECT id,email FROM users WHERE id=?').get(targetId);if(!target)return json(request,{error:'User not found.'},404);if(target.email.toLowerCase()===ownerEmail)return json(request,{error:'The owner account cannot be deleted.'},403);db.prepare('INSERT INTO moderation_log(admin_id,action,target_type,target_id) VALUES(?,?,?,?)').run(admin.id,'delete','user',targetId);db.prepare('DELETE FROM users WHERE id=?').run(targetId);return json(request,{ok:true})}
  return json(request,{error:'Not found.'},404);
}
function login(request,userId){const token=randomBytes(32).toString('hex');db.prepare("INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,datetime('now','+30 days'))").run(token,userId);const origin=request.headers.get('origin');const crossOrigin=origin&&new URL(origin).origin!==new URL(request.url).origin;const policy=crossOrigin?'; SameSite=None; Secure':'; SameSite=Lax';return json(request,{user:privateUser(userId),token},200,{'Set-Cookie':`social_session=${token}; Path=/; HttpOnly${policy}; Max-Age=2592000`})}
export function closeSocialDatabaseForTests(){if(process.env.NODE_ENV!=='test')throw new Error('Test-only database shutdown is unavailable.');db.close()}
export default {async fetch(request){try{return await route(request)}catch(e){return json(request,{error:e.message||'Something went wrong.'},e.status||500)}}};
